name: Format the Rust Code
on:
  pull_request: 
  push: 
    branches: [ "main" ]

jobs:
  fmt: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format all Cargo.toml files
        run: |
          find . -name "Cargo.toml" -print0 | xargs -0 -n1 -P4 cargo fmt --manifest-path -- --check
